### ISSUE TITLE
Overwritten symbol text values not included in the JSON

### ISSUE THREAD

**Issue by hiqjan** [xaviervia/sketch2json#4] opened 2017-04-26 14:05 UTC
I cannot find overwritten symbol text values anywhere from the created JSON. I'm going through all attributedString properties and converting _archive texts to plain text  (with base64 decoding and bplist parser). Still no luck finding the overwritten text value.

Maybe I'm missing something or haven't looked form rigth place.

**Comment by xaviervia** [comment] 2017-04-28 01:26
Hi! Sorry for the late reply. Unfortunately I'm on vacation and have no access to a workstation where to dig in the issue, I will do so next week.

Regarding the problem itself, I assumed as well those would be inside the _archive blobs, but I haven't tried this with a file that had symbol overrides. I'm surprised they are not there. Would you mind sharing a simple example file that has overrides to reproduce?

Also, since we are on the topic, do you think it would be valuable to base64 decode the _archive blobs as part of this tool? I started with a vanilla approach of just loading the JSON (even images are excluded) but I'm starting to I think that it might be more useful to expand those as well.

**Comment by xaviervia** [comment] 2017-06-30 09:54
Closing for now, let me know if you have an example that I can take a loot at :)

**Closed as completed by xaviervia** 2017-06-30 09:54 UTC
